sonar.projectKey=arena-ufrn
sonar.projectName=Arena UFRN
sonar.projectVersion=0.1.0

sonar.sources=backend/src,frontend/src

sonar.tests=backend/tests

sonar.test.inclusions=backend/tests/**/*.test.js
sonar.exclusions=**/node_modules/**,**/coverage/**,**/generated/**,**/dist/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.scm.provider=git
sonar.sourceEncoding=UTF-8